### PR TITLE
Migrated to Sound Null Safety

### LINKED ISSUE #43: Null Safety

### PR DESCRIPTION
**Pull request by nagoya0**
This PR adds null safety to this package.

Closes #43

### CODE REVIEW

**Comment by andzejsw** [comment]
@itzmeanjan ?

**Comment by GroovinChip** [comment]
@itzmeanjan any word on this?

@nagoya0 if this plugin is abandoned, perhaps you should publish your null-safe version to pub.

**Comment by GroovinChip** [comment]
@itzmeanjan @nagoya0 please provide an update on this matter, if you'd be so kind.

**Comment by nagoya0** [comment]
I'm sorry, but I don't think I'll be able to manage the repository for the long term, so I don't want to publish a new alternative package...
It's okay for someone to fork my branch and publish a new package! ;)

**Pull request closed without merging**
